version: '3.9'

networks:
  main-network:
    name: main-network
    external: false
    driver: bridge
services:

  pipelineforbackend:
    image: ghcr.io/zin-lr/pipelineforbackend:dev
    container_name: backend-container
    volumes:
      - ./storage:/storage
    networks:
      - main-network
    restart: always
    ports:
      - "8080:8080"