name: backen CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - master1


env:
  IMAGE_TAG: dev
  BRANCH_NAME: main
  SERVICE_NAME: pipelineforbackend
  COMPOSE_DIR: docker-compose.yml
  WORKDIR: ~/github_actions/pipelineforBackend

jobs:

  builder:
    name: "Build & Push docker image"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: ./.github/workflows/composite/jib
        with:
          image_name: ${{ secrets.REGISTRY_ENDPOINT }}/${{ env.SERVICE_NAME }}:${{ env.IMAGE_TAG }} # ghcr.io/imadfa01 | backend-cicd | dev
          service_name: ${{ env.SERVICE_NAME }}
          registry_host: ${{ secrets.REGISTRY_HOST }}
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.REGISTRY_GIT_PATH }}